modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "creatorminecraft"
version = "${version}"
displayName = "Creator Minecraft Java"
authors = "ExtremeMakerX"
description = '''It merges the capabilities of 3D software and it has MTR creator features that allow a user to create models faster and more efficiently!'''
#logoFile = ""

[[dependencies.creatorminecraft]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creatorminecraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creatorminecraft]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"