modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "creatorminecraft"
version = "1.20.2-1.0.1-pre-alpha"
displayName = "Creator Minecraft Java"
authors = "ExtremeMakerX"
description = '''It merges the capabilities of 3D software and it has MTR creator features that allow a user to create models faster and more efficiently!'''
logoFile = "creator_icon.png"

[[dependencies.creatorminecraft]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creatorminecraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2]"
ordering = "NONE"
side = "BOTH"
