package creatorminecraft.client;

public interface CreatorIGUI {
    int PIXEL_SIZE = 1;
    int PIXEL_X2_SIZE = 2;
    int TINY_SQUARE = 5;
    int HALF_SQUARE_SIZE = 10;
    int STANDARD_SIZE = 20;
    int BIG_SQUARE_SIZE = 40;
    int GIANT_SQUARE_SIZE = 80;
    int SUPER_GIANT_SQUARE_SIZE = 200;

    int ARGB_WHITE = 0xFFFFFFFF;
    int ARGB_BLACK = 0xFF000000;
    int ARGB_WHITE_TRANSLUCENT = 0x7FFFFFFF;
    int ARGB_BLACK_TRANSLUCENT = 0x7F000000;
    int ARGB_LIGHT_GRAY = 0xFFAAAAAA;
    int ARGB_GRAY = 0xFF666666;
    int ARGB_DARK_MID_GRAY = 0xFF4D4D4D;
    int ARGB_DARK_GRAY = 0xFF232323;
    int ARGB_DARK = 0xFF191919;
    int ARGB_DARK_BLACK = 0xFF0A0A0A;
}
