# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on: [pull_request, push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        loader: [quilt, fabric-like, fabric, forge, common]
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build ${{ matrix.loader }}
        run: ./gradlew ${{ matrix.loader }}:build ${{ matrix.loader }}:jar
      - name: Rename Jar File artifact
        if: matrix.loader != 'common' && matrix.loader != 'fabric-like'
        run: mv ${{ matrix.loader }}/build/libs/creatorminecraft-1.1.0-alpha.jar ${{ matrix.loader }}/build/libs/creatorminecraft-${{ matrix.loader }}-${{ env.minecraft_version }}-1.1.0-alpha.jar
      - name: Capture release artifacts
        if: matrix.loader != 'common' && matrix.loader != 'fabric-like'
        uses: actions/upload-artifact@main
        with:
          name: Jar Files - ${{ matrix.loader }}
          path: ${{ matrix.loader }}/build/libs/