# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        minecraft: [1.20.4]
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@main
      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Setup Fabric files
        run: ./gradlew fabric:remapJar -PminecraftVersion="${{ matrix.minecraft }}"
      - name: Setup Forge files
        run: ./gradlew forge:remapJar -PminecraftVersion="${{ matrix.minecraft }}"
      - name: Build ${{ matrix.minecraft }}
        run: ./gradlew build -PminecraftVersion="${{ matrix.minecraft }}"
      - name: Capture release artifacts
        uses: actions/upload-artifact@main
        with:
          name: Fabric and Forge ${{ matrix.minecraft }}
          path: build/release/