# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        minecraft: [1.20.4]
        loader: [ fabric, forge, common ]
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build ${{ matrix.minecraft }} ${{ matrix.loader }}
        run: ./gradlew ${{ matrix.loader }}:build -PbuildVersion="${{ matrix.minecraft }}"
      - name: Capture release artifacts
        if: matrix.loader != 'common'
        uses: actions/upload-artifact@v2
        with:
          name: Fabric and Forge
          path: build/release/
      - name: Capture lib artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Libraries
          path: build/libs/