# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on: [pull_request, push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        loader: [quilt, fabric-like, fabric, forge, common ]
    #runs-on: self-hosted
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build ${{ matrix.loader }}
        run: ./gradlew ${{ matrix.loader }}:build ${{ matrix.loader }}:jar
      - name: Capture release artifacts
        if: matrix.loader != 'common' & matrix.loader != 'fabric-like'
        uses: actions/upload-artifact@v2
        with:
          name: "Jar Files - ${{ matrix.loader }}"
          path: |
            ${{ matrix.loader }}/build/libs/creatorminecraft-1.1.0-alpha-${{ matrix.loader }}.jar
            !${{ matrix.loader }}/build/libs/
            !${{ matrix.loader }}/**/*-dev.jar
            !${{ matrix.loader }}/**/*-shadow.jar
            !${{ matrix.loader }}/**/*-transformProduction*.jar