# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on: [pull_request, push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        loader: [quilt, fabric-like, fabric, forge, common ]
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@main
         - name: Setup JDK 17
          runs-on: ubuntu-latest
          steps:
            - name: Make gradle wrapper executable
              run: chmod +x ./gradlew
            - name: Build Quilt
              run: |
                cd quilt
                ./gradlew build jar
            - name: Build Fabric
              run: |
                cd fabric
                ./gradlew build jar
            - name: Build Forge
              run: |
                cd forge
                ./gradlew build jar
            - name: Build Common
              run: |
                cd common
                ./gradlew build jar
            - name: Capture lib artifacts
              if: matrix.loader != 'common' && matrix.loader != 'fabric-like'
              uses: actions/upload-artifact@main
              with:
                name: Jar Files
                path: |
                  **/build/libs/creatorminecraft-1.1.0-alpha-${{ matrix.loader }}.jar
                  !build/libs/
                  !**/*-dev.jar
                  !**/*-shadow.jar
                  !**/*-transformProduction*.jar